### ISSUE TITLE
能否爬取一些额外信息，例如以下信息

### ISSUE THREAD

**Issue by Chengke123** [aglorice/CtripSpider#5]
![image](https://github.com/user-attachments/assets/ca40501c-23b2-46f7-ba3f-86a089ac188e)

**Comment by aglorice** [comment]
`scene_info.json`里有关于景点的额外信息，包括星级，评论数量，评分等。因为本项目是主要爬取评论，所以没有爬取过多的信息，看了下你发的这个，理论上应该可以可以。
